services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: adminpostgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: banco
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: addministrador@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin123

    volumes:
    - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

 # microservicio:
 #   build:
 #     context: .
 #     dockerfile: Dockerfile
 #   container_name: microservicio_container
 #   ports:
 #     - "8081:8080"
 #   depends_on:
 #     - postgres
 #   environment:
 #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banco
 #     SPRING_DATASOURCE_USERNAME: adminpostgres
 #     SPRING_DATASOURCE_PASSWORD: admin123
 #   networks:
 #     - backend


networks:
  backend:
