services:
  postgres:
    image: postgres:17
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: adminpostgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: banco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: addministrador@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: